"""Extract text from downloaded Rencai corpus files.

This script reads the newest download manifest generated by the Chrome
extension, extracts text from supported local files, and writes output under
data/rencai/text. Optional packages improve coverage:

    pip install -r requirements-corpus.txt
"""

from __future__ import annotations

import argparse
import csv
import json
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Callable


@dataclass
class ExtractResult:
    status: str
    text: str = ""
    error: str = ""


def newest_manifest(manifest_dir: Path) -> Path:
    manifests = sorted(
        manifest_dir.glob("download-manifest-*.json"),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )
    if not manifests:
        raise FileNotFoundError(f"No download-manifest-*.json found in {manifest_dir}")
    return manifests[0]


def safe_text_name(local_path: str, resource_id: str) -> str:
    stem = Path(local_path).stem or resource_id
    stem = re.sub(r"[^A-Za-z0-9_. -]+", "_", stem).strip(" .")
    return f"{resource_id}-{stem[:90]}.txt"


def extract_pdf(path: Path) -> ExtractResult:
    try:
        from pypdf import PdfReader  # type: ignore
    except Exception as exc:
        return ExtractResult("missing_dependency", error=f"pypdf not installed: {exc}")

    try:
        reader = PdfReader(str(path))
        parts = []
        for page in reader.pages:
            parts.append(page.extract_text() or "")
        return ExtractResult("ok", "\n\n".join(parts).strip())
    except Exception as exc:
        return ExtractResult("error", error=str(exc))


def extract_docx(path: Path) -> ExtractResult:
    try:
        import docx  # type: ignore
    except Exception as exc:
        return ExtractResult("missing_dependency", error=f"python-docx not installed: {exc}")

    try:
        document = docx.Document(str(path))
        text = "\n".join(paragraph.text for paragraph in document.paragraphs)
        return ExtractResult("ok", text.strip())
    except Exception as exc:
        return ExtractResult("error", error=str(exc))


def extract_xlsx(path: Path) -> ExtractResult:
    try:
        from openpyxl import load_workbook  # type: ignore
    except Exception as exc:
        return ExtractResult("missing_dependency", error=f"openpyxl not installed: {exc}")

    try:
        workbook = load_workbook(str(path), read_only=True, data_only=True)
        lines = []
        for sheet in workbook.worksheets:
            lines.append(f"# {sheet.title}")
            for row in sheet.iter_rows(values_only=True):
                values = [str(value) for value in row if value not in (None, "")]
                if values:
                    lines.append("\t".join(values))
        return ExtractResult("ok", "\n".join(lines).strip())
    except Exception as exc:
        return ExtractResult("error", error=str(exc))


def extract_plain(path: Path) -> ExtractResult:
    try:
        return ExtractResult("ok", path.read_text(encoding="utf-8", errors="ignore").strip())
    except Exception as exc:
        return ExtractResult("error", error=str(exc))


def extractor_for(path: Path) -> Callable[[Path], ExtractResult]:
    suffix = path.suffix.lower()
    if suffix == ".pdf":
        return extract_pdf
    if suffix in {".docx", ".doc"}:
        return extract_docx
    if suffix in {".xlsx", ".xls", ".csv"}:
        return extract_xlsx if suffix != ".csv" else extract_plain
    if suffix in {".txt", ".md", ".rtf"}:
        return extract_plain
    return lambda _: ExtractResult("unsupported", error=f"Unsupported extension: {suffix}")


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument("--manifest", default="", help="Specific download manifest JSON")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    rencai = root / "data" / "rencai"
    manifest_path = Path(args.manifest).resolve() if args.manifest else newest_manifest(rencai / "manifests")
    text_dir = rencai / "text"
    manifest_dir = rencai / "manifests"
    text_dir.mkdir(parents=True, exist_ok=True)
    manifest_dir.mkdir(parents=True, exist_ok=True)

    records = json.loads(manifest_path.read_text(encoding="utf-8"))
    output_rows: list[dict[str, object]] = []

    for record in records:
        local_path = root / record["local_path"]
        resource_id = record.get("id", "resource")
        text_name = safe_text_name(record.get("local_path", ""), resource_id)
        text_path = text_dir / text_name

        if not local_path.exists():
            result = ExtractResult("missing_file", error=f"Missing file: {local_path}")
        else:
            result = extractor_for(local_path)(local_path)
            if result.text:
                text_path.write_text(result.text, encoding="utf-8")

        output_rows.append(
            {
                "id": resource_id,
                "title": record.get("title", ""),
                "source_page": record.get("source_page", ""),
                "local_path": record.get("local_path", ""),
                "text_path": str(text_path.relative_to(root)).replace("\\", "/") if result.text else "",
                "status": result.status,
                "chars": len(result.text),
                "error": result.error,
            }
        )

    stamp = datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    json_path = manifest_dir / f"text-manifest-{stamp}.json"
    csv_path = manifest_dir / f"text-manifest-{stamp}.csv"
    json_path.write_text(json.dumps(output_rows, indent=2), encoding="utf-8")
    write_csv(csv_path, output_rows)

    ok = sum(1 for row in output_rows if row["status"] == "ok")
    print(f"Processed {len(output_rows)} files; extracted text from {ok}.")
    print(f"Wrote {json_path}")
    print(f"Wrote {csv_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
